/**
 * F9 edit/delete application logic — MVP-SPEC.md §5 F9 / §6 S5.
 *
 * Pure: no storage, no React, no `Date` — same discipline as `entryActions.ts`
 * (`useTownStore.ts` does the storage side effects). Reuses `entryActions.ts`'s
 * `adjustSavings` (F13 back-out/forward) and `decideBuildOrQueue` (F2/F4/F14's
 * build-or-queue decision) rather than re-deriving either — round-4 finding
 * C3 flagged both as hand-rolled duplicates of logic this file's neighbour
 * already owns.
 *
 * `type` IS editable (round-4 finding C1) via three cases:
 *  - type unchanged: amount/memo/date/category edits, as before.
 *  - neither old nor new type is "saving" (지출 <-> 수입): both consume a slot
 *    identically (F2), so this is just a category/type re-skin on whatever
 *    building or queued material the entry already produced — no slot
 *    accounting changes at all.
 *  - 저축 -> 지출/수입: never had a building; decide build-or-queue fresh,
 *    exactly like a brand-new F1 save (`decideBuildOrQueue`), minus streak
 *    credit — an edit is not a new logging act.
 *  - 지출/수입 -> 저축: loses whatever building/queue slot it already
 *    produced (D-10's delete policy: not refunded) and starts contributing
 *    to the tower instead.
 */
import { adjustSavings, decideBuildOrQueue } from "./entryActions";
import type { Building, CategoryId, EntryType, LedgerEntry, QueuedMaterial, TownState } from "./types";

/** Locates the building this entry produced, if any — the one place both delete and edit look this up (round-4 finding C3: was copy-pasted twice in `useTownStore.ts`). */
export function buildingForEntry(buildings: readonly Building[], entryId: string): Building | undefined {
  return buildings.find((b) => b.source.kind === "entry" && b.source.entryId === entryId);
}

/** Drops `entryId`'s pending material from the queue, if any — the F14 invariant "every queued material has a live entry" (round-4 finding C2), needed by both delete and an edit that moves the entry out of "still needs a building" state (saving -> already handled by never having queued; 저축 entries never queue). */
function dropFromQueue(town: TownState, entryId: string): TownState {
  if (!town.queue.some((m) => m.entryId === entryId)) return town;
  return { ...town, queue: town.queue.filter((m) => m.entryId !== entryId) };
}

export interface DeleteEntryArgs {
  town: TownState;
  buildings: readonly Building[];
  entry: LedgerEntry;
}

export interface DeleteEntryResult {
  town: TownState;
  buildings: Building[];
  /** The removed building's id/`builtOn` month, for the caller to also drop it from that month's storage chunk — `null` when the entry never built one. */
  removedBuilding: { id: string; ym: string } | null;
}

/**
 * F9 delete: removes the entry's building (if any — building count -1, its
 * plot becomes a permanent empty lot, the slot is NOT refunded per D-10) and,
 * for a still-queued entry (F14), drops its material from `town.queue` so a
 * later drain never builds a ghost for an entry that no longer exists
 * (round-4 finding C2 — the fix this task's escalation named as highest
 * value). A deleted 저축 entry backs its amount out of the tower.
 */
export function deleteEntryEffects({ town, buildings, entry }: DeleteEntryArgs): DeleteEntryResult {
  let nextTown = town;
  let nextBuildings = buildings as Building[];
  let removedBuilding: DeleteEntryResult["removedBuilding"] = null;

  const bound = buildingForEntry(buildings, entry.id);
  if (bound) {
    nextBuildings = buildings.filter((b) => b.id !== bound.id);
    removedBuilding = { id: bound.id, ym: bound.builtOn.slice(0, 7) };
  }

  if (entry.queued) nextTown = dropFromQueue(nextTown, entry.id);
  if (entry.type === "saving") nextTown = adjustSavings(nextTown, entry.categoryId, -entry.amountKrw);

  return { town: nextTown, buildings: nextBuildings, removedBuilding };
}

/** F9 edit fields — `type` included (round-4 finding C1: was display-only). */
export interface EntryEditPatch {
  type?: EntryType;
  amountKrw?: number;
  categoryId?: CategoryId;
  occurredOn?: string;
  memo?: string;
}

export interface EditEntryArgs {
  town: TownState;
  buildings: readonly Building[];
  entry: LedgerEntry;
  patch: EntryEditPatch;
  today: string;
  dailyBuildSlots: number;
  materialQueueMax: number;
  tierThresholds: readonly number[];
  /** Used ONLY when this edit newly places a building (저축 -> 지출/수입) — generated by the caller exactly like a fresh F1 save. */
  newBuildingId: string;
  variantIndex: number;
  plotIndex: number;
  now: number;
}

export interface EditEntryResult {
  entry: LedgerEntry;
  town: TownState;
  buildings: Building[];
  removedBuilding: { id: string; ym: string } | null;
  /** A building this edit newly placed (저축 -> 지출/수입 landing on an open slot) — the caller persists it into TODAY's month chunk, same as a fresh save. */
  newBuilding: Building | null;
}

export function editEntryEffects(args: EditEntryArgs): EditEntryResult {
  const { entry: oldEntry, patch, today, dailyBuildSlots, materialQueueMax, tierThresholds, newBuildingId, variantIndex, plotIndex, now } = args;

  const newType = patch.type ?? oldEntry.type;
  const newCategoryId = patch.categoryId ?? oldEntry.categoryId;
  const newAmountKrw = patch.amountKrw ?? oldEntry.amountKrw;
  const newOccurredOn = patch.occurredOn ?? oldEntry.occurredOn;
  const newMemo = "memo" in patch ? patch.memo : oldEntry.memo;
  const newYm = newOccurredOn.slice(0, 7);
  const categoryChanged = patch.categoryId !== undefined && patch.categoryId !== oldEntry.categoryId;
  const dateChanged = patch.occurredOn !== undefined && patch.occurredOn !== oldEntry.occurredOn;

  let town = args.town;
  let buildings = args.buildings as Building[];
  let removedBuilding: EditEntryResult["removedBuilding"] = null;
  let newBuilding: Building | null = null;
  let buildingId = oldEntry.buildingId;
  let queued = oldEntry.queued;

  const wasSaving = oldEntry.type === "saving";
  const willBeSaving = newType === "saving";
  const bound = buildingForEntry(buildings, oldEntry.id);

  if (newType === oldEntry.type) {
    // Amount/memo/date edits never move the building (spec); a category
    // change re-skins it in place, keeping the same plot.
    if (bound && categoryChanged) {
      const updated: Building = { ...bound, categoryId: newCategoryId };
      buildings = buildings.map((b) => (b.id === bound.id ? updated : b));
    }
    // F14 (round-4 finding C2): a still-queued material follows the same
    // category/date edits its future building would have gotten.
    if (queued && (categoryChanged || dateChanged)) {
      town = {
        ...town,
        queue: town.queue.map((m): QueuedMaterial => (m.entryId === oldEntry.id ? { ...m, categoryId: newCategoryId, entryYm: newYm } : m)),
      };
    }
    if (wasSaving && (categoryChanged || (patch.amountKrw !== undefined && patch.amountKrw !== oldEntry.amountKrw))) {
      town = adjustSavings(town, oldEntry.categoryId, -oldEntry.amountKrw);
      town = adjustSavings(town, newCategoryId, newAmountKrw);
    }
  } else if (!wasSaving && !willBeSaving) {
    // 지출 <-> 수입: identical slot mechanics (F2) — a type flip is just a
    // category/type re-skin of whatever this entry already produced.
    if (bound) {
      const updated: Building = { ...bound, categoryId: newCategoryId };
      buildings = buildings.map((b) => (b.id === bound.id ? updated : b));
    }
    if (queued) {
      town = {
        ...town,
        queue: town.queue.map((m): QueuedMaterial => (m.entryId === oldEntry.id ? { ...m, categoryId: newCategoryId, entryYm: newYm } : m)),
      };
    }
  } else if (wasSaving && !willBeSaving) {
    // 저축 -> 지출/수입: never built or queued — decide fresh (reuses F2/F4's
    // own decision function; no streak credit, this is an edit, not a new act).
    town = adjustSavings(town, oldEntry.categoryId, -oldEntry.amountKrw);
    const decision = decideBuildOrQueue({
      town,
      buildingCountBeforeThis: buildings.length,
      today,
      dailyBuildSlots,
      materialQueueMax,
      tierThresholds,
      entryId: oldEntry.id,
      categoryId: newCategoryId,
      variantIndex,
      buildingId: newBuildingId,
      plotIndex,
      createdAt: now,
      entryYm: newYm,
      advancesStreak: false,
    });
    town = decision.town;
    if (decision.building) {
      newBuilding = decision.building;
      buildings = [...buildings, decision.building];
      buildingId = decision.building.id;
      queued = false;
    } else if (decision.queuedMaterial) {
      buildingId = null;
      queued = true;
    } else {
      buildingId = null;
      queued = false;
    }
  } else {
    // 지출/수입 -> 저축: loses its building/queued slot (D-10: not refunded), starts contributing to the tower.
    if (bound) {
      buildings = buildings.filter((b) => b.id !== bound.id);
      removedBuilding = { id: bound.id, ym: bound.builtOn.slice(0, 7) };
    }
    if (queued) town = dropFromQueue(town, oldEntry.id);
    buildingId = null;
    queued = false;
    town = adjustSavings(town, newCategoryId, newAmountKrw);
  }

  const entry: LedgerEntry = {
    ...oldEntry,
    type: newType,
    amountKrw: newAmountKrw,
    categoryId: newCategoryId,
    occurredOn: newOccurredOn,
    memo: newMemo,
    updatedAt: now,
    buildingId,
    queued,
  };

  return { entry, town, buildings, removedBuilding, newBuilding };
}
